Vagrant.configure("2") do |config|
  config.vm.define "ws01.staging.fale.io" do |ws01s|
    ws01s.vm.hostname = "ws01.staging.fale.io"
    ws01s.vm.box = "centos/7"
  end
  config.vm.define "ws02.staging.fale.io" do |ws02s|
    ws02s.vm.hostname = "ws02.staging.fale.io"
    ws02s.vm.box = "centos/7"
  end
  config.vm.define "db01.staging.fale.io" do |db01s|
    db01s.vm.hostname = "db01.staging.fale.io"
    db01s.vm.box = "centos/7"
  end
  config.vm.define "ws01.fale.io" do |ws01|
    ws01.vm.hostname = "ws01.fale.io"
    ws01.vm.box = "centos/7"
  end
  config.vm.define "ws02.fale.io" do |ws02|
    ws02.vm.hostname = "ws02.fale.io"
    ws02.vm.box = "centos/7"
  end
  config.vm.define "db01.fale.io" do |db01|
    db01.vm.hostname = "db01.fale.io"
    db01.vm.box = "centos/7"
  end
  config.vm.define "builder01.fale.io" do |builder01|
    builder01.vm.hostname = "builder01.fale.io"
    builder01.vm.box = "centos/7"
  end
end
